// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AppLogo: typeof import('./../components/AppLogo.vue')['default']
    BaseChart: typeof import('./../components/UI/BaseChart.vue')['default']
    BaseInput: typeof import('./../components/UI/Form/BaseInput.vue')['default']
    BaseLoadingButton: typeof import('./../components/UI/BaseLoadingButton.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    HistChart: typeof import('./../components/modules/ECharts/HistChart.vue')['default']
    IconCheckOne: typeof import('@icon-park/vue-next')['CheckOne']
    IconLock: typeof import('@icon-park/vue-next')['Lock']
    IconMoon: typeof import('@icon-park/vue-next')['Moon']
    IconPic: typeof import('@icon-park/vue-next')['Pic']
    IconSun: typeof import('@icon-park/vue-next')['Sun']
    IconUser: typeof import('@icon-park/vue-next')['User']
    LineChart: typeof import('./../components/modules/ECharts/LineChart.vue')['default']
    MixedChart: typeof import('./../components/modules/ECharts/MixedChart.vue')['default']
    PaginatedTable: typeof import('./../components/UI/PaginatedTable.vue')['default']
    PieChart: typeof import('./../components/modules/ECharts/PieChart.vue')['default']
    ProductForm: typeof import('./../components/ProductForm.vue')['default']
    TableActionButton: typeof import('./../components/UI/TableActionButton.vue')['default']
    TheBreadcrumb: typeof import('./../components/TheBreadcrumb.vue')['default']
    TheHeading: typeof import('./../components/TheHeading.vue')['default']
    TheSidebar: typeof import('./../components/TheSidebar.vue')['default']
    TheSidebarItem: typeof import('./../components/TheSidebarItem.vue')['default']
    VanButton: typeof import('vant/es')['Button']
  }
}

export { }
